### ISSUE TITLE
How can i get this app

### ISSUE THREAD

**Issue by erkam2002** [ImagicalMine/IM-Android#1]
How download is this?

**Comment by MasterWolf** [comment]
its in releases folder. lol,

**Comment by erkam2002** [comment]
But this is Genisys

**Comment by MasterWolf** [comment]
Did you read README?

**Comment by MasterWolf** [comment]
•This program was originally designed for Genisys, then modified for ImagicalMine.

**Comment by erkam2002** [comment]
Ok
