### ISSUE TITLE
Didn't install Genisys?

### ISSUE THREAD

**Issue by YoutubeESG12** [ImagicalMine/IM-Android#5]
I get this error everytime!

Genisys Android v0.2.5 alpha
Powered by iTX Technologies

Workspace: /sdcard/Genisys/

a. Init Genisys Android from zips
[NOTICE] Put php.zip and Genisys.zip into /sdcard/Genisys/
b. Launch Genisys
c. Set workspace
d. Edit php.ini
e. Rewrite php.ini

i. About Genisys Android

Select: b

[NOTICE] Now loading ...

[ERROR] Genisys has not been installed !

Press enter to continue ...

**Comment by keithkfng** [comment]
Don't use the APK.

**Comment by YoutubeESG12** [comment]
So what so I use?
